### ISSUE TITLE
effect.twisted.perform_parallel can be generalized for any async performers

### ISSUE THREAD

**Issue by tomprince** [radix/effect#19]
``perform_parallel`` just adds callbacks to all the provide effects, to capture there results, and then runs each of the effects in sequence. In addition, although the implementation uses twisted, it could just [use](https://github.com/tomprince/effect/compare/generic-parallel) the native asynchronous support of effect.

That is, it converts from effects to deferreds, calls `gatherResults` on the deferreds and the converts back to an effect. This could just as easily be handled without the detour through twisted code.

**Comment by radix** [comment]
PR at #31.

**Comment by radix** [comment]
And this is done.
